---
analyze_business_idea_task:
  description: Analyze the startup concept provided in {business_idea} along with
    the background provided in {entrepreneur_background}. Identify key strengths,
    potential weaknesses, opportunities for scalability, and inherent risks associated
    with the startup idea.
  expected_output: A detailed analysis report highlighting the strengths, weaknesses,
    scalability prospects, and risks linked to {business_idea} with context from {entrepreneur_background}.
  async_execution: false
  agent: business_analyst
conduct_market_research_task:
  description: Perform market research based on {business_idea} to infer competitive
    landscape. Identify competitors, analyze industry trends, and pinpoint market
    gaps that could affect the startup's potential.
  expected_output: A comprehensive market research report that presents identified
    competitors, key industry trends, and market gaps relevant to {business_idea}.
  async_execution: false
  agent: market_researcher
generate_financial_projections_task:
  description: Develop high-level financial projections using inputs from {business_idea}
    and {entrepreneur_background}. Incorporate insights from the market research (from
    conduct_market_research_task) to estimate revenue potential, projected expenses,
    and break-even points.
  expected_output: A financial forecast report that includes revenue estimates, expense
    projections, and break-even analysis, integrating market trends and competitor
    data from the earlier market research.
  async_execution: false
  agent: financial_forecaster
  context:
  - conduct_market_research_task
validate_and_compile_startup_viability_task:
  description: |
    Analyze {business_idea} and {entrepreneur_background} to create a structured validation report.
    
    Return the analysis in this exact JSON structure:
    
    {{
      "startup_validation_report": {{
        "business_idea": "<string>",
        "entrepreneur_background": "<string>",
        "viability_score": {{
          "overall_score": <float 0-100>,
          "breakdown": {{
            "market_demand": {{
              "score": <float 0-100>,
              "weight": 0.30,
              "explanation": "<string>",
              "factors": {{
                "market_size": "<string>",
                "growth_rate": "<string>",
                "consumer_interest": "<string>"
              }}
            }},
            "competitive_landscape": {{
              "score": <float 0-100>,
              "weight": 0.25,
              "explanation": "<string>",
              "factors": {{
                "competitor_count": <integer>,
                "differentiation_level": "<string>",
                "barriers_to_entry": "<string>"
              }}
            }},
            "financial_viability": {{
              "score": <float 0-100>,
              "weight": 0.25,
              "explanation": "<string>",
              "factors": {{
                "revenue_potential": "<string>",
                "cost_structure": "<string>",
                "profitability_timeline": "<string>"
              }}
            }},
            "scalability": {{
              "score": <float 0-100>,
              "weight": 0.10,
              "explanation": "<string>",
              "factors": {{
                "growth_potential": "<string>",
                "automation_feasibility": "<string>",
                "market_expansion": "<string>"
              }}
            }},
            "risk_factors": {{
              "score": <float 0-100>,
              "weight": 0.10,
              "explanation": "<string>",
              "factors": {{
                "legal_risks": "<string>",
                "technical_risks": "<string>",
                "operational_risks": "<string>"
              }}
            }}
          }}
        }},
        "market_analysis": {{
          "industry_size": "<string>",
          "growth_trends": "<string>",
          "target_customers": "<string>",
          "key_market_shifts": "<string>"
        }},
        "similar_companies": [
          {{
            "company_name": "<string>",
            "similarity_score": <integer 0-100>,
            "key_features": {{
              "unique_selling_points": "<string>",
              "challenges": "<string>",
              "strengths": "<string>"
            }},
            "comparison_to_business_idea": "<string>"
          }}
        ],
        "financial_projections": {{
          "startup_costs": {{
            "inventory": <float>,
            "technology": <float>,
            "marketing": <float>,
            "legal": <float>,
            "operations": <float>,
            "total_startup_cost": <float>
          }},
          "revenue_expense_forecast": {{
            "quarterly_projection": [
              {{
                "quarter": "<string>",
                "projected_revenue": <float>,
                "projected_expenses": <float>
              }}
            ]
          }},
          "key_financial_metrics": {{
            "customer_acquisition_cost": <float>,
            "lifetime_value": <float>,
            "churn_rate": <float>,
            "average_subscription_length": <float>
          }},
          "break_even_point": {{
            "time_to_profitability": "<string>",
            "total_revenue_at_breakeven": <float>,
            "total_expenses_at_breakeven": <float>
          }}
        }},
        "actionable_recommendations": {{
          "market_positioning": "<string>",
          "financial_improvements": "<string>",
          "risk_mitigation": "<string>",
          "growth_strategy": "<string>"
        }}
      }}
    }}

    Base all analyses on the outputs from analyze_business_idea_task, conduct_market_research_task, and generate_financial_projections_task.
    Ensure all numerical values are properly calculated and all text fields provide clear, concise insights.

  expected_output: "A JSON object following the exact structure specified above, with all fields populated with relevant data"
  async_execution: false
  agent: ai_validator
  context:
    - analyze_business_idea_task
    - conduct_market_research_task
    - generate_financial_projections_task
